disabled_rules: # rule identifiers turned on by default to exclude from running
  - colon
  - comma
  - control_statement
  - line_length
  - empty_parameters
  - vertical_whitespace
opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - empty_count
excluded:
- Carthage
- Pods
